<div class="modal fade" id="organizationSearchSelectModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3 class="modal-title" id="myModalLabel">Search Groups</h3>
            </div>
            <div class="modal-body">
                <?=$this->render('search/search/organization-select'); ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

function searchOrganizations(query) {
    $.ajax({
        url: "/search/organization-select/" + query,
    }).done(function(html) {
        $("div#organizationSearchSelectModal").find(".modal-body").html(html);
    });
}
$(document).ready(function() {
    var query = <?= trim($this->query) ? '"' . $this->query . '"' : 'false'; ?>;
    if (query) {
        searchOrganizations(query);
    }
    $('div#organizationSearchSelectModal').on('click', 'a.group', function() {
        var groupId = $(this).data('group_id');
        var groupName = $(this).data('group_name');
        $('.selected_group_id_target').val(groupId).removeClass('selected_group_id_target');
        $('.selected_group_name_target').val(groupName).removeClass('selected_group_name_target');
        $('div#organizationSearchSelectModal').modal('hide');
    });
    $('div#organizationSearchSelectModal').on('submit', "form#search-organization-form", function(e) {
        e.preventDefault()
        var query = $(this).find('input[name="query"]').val();
        searchOrganizations(query);
    });
});

</script>
